package javaapplication53;

import java.util.Random;

public class Bilgisayar_Bilgisayar extends javax.swing.JFrame {

   Bilgisayar bilgisayar1= new Bilgisayar();
   Bilgisayar oyuncu1= new Bilgisayar();
   Bilgisayar bilgisayartemp= new Bilgisayar();
    
    int hamlesayisi=0;
    
    double oyuncudayanikliliksayac=0;
    double bilgisayardayanikliliksayac=0;
    
    public Bilgisayar_Bilgisayar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hamleyap = new javax.swing.JButton();
        nesneolustur1 = new javax.swing.JButton();
        nesneolustur2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        jTextField1.setBackground(new java.awt.Color(255, 102, 204));
        jTextField1.setText("   Bilgisayar1");

        jTextField2.setBackground(new java.awt.Color(255, 102, 204));
        jTextField2.setText("    Bilgisayar2");

        jLabel1.setText("Seçilen Nesne");

        jLabel2.setText("Seçilen Nesne");

        hamleyap.setBackground(new java.awt.Color(204, 0, 204));
        hamleyap.setText("HAMLE YAP");
        hamleyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamleyapActionPerformed(evt);
            }
        });

        nesneolustur1.setText("Nesne Oluştur");
        nesneolustur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nesneolustur1ActionPerformed(evt);
            }
        });

        nesneolustur2.setText("Nesne Oluştur");
        nesneolustur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nesneolustur2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Dayanıklılık");

        jTextField4.setText("Seviye Puanı");

        jTextField5.setText("Dayanıklılık");

        jTextField6.setText("Seviye Puanı");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nesneolustur1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nesneolustur2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(hamleyap))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nesneolustur2)
                    .addComponent(nesneolustur1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hamleyap)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nesneolustur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nesneolustur1ActionPerformed
        // TODO add your handling code here:
        Tas tasb= new Tas(20.0,0,"Tas",2);
        Kagit kagitb= new Kagit(20.0,0,"Kagit",2);
        Makas makasb= new Makas(20.0,0,"Makas",2);
        
        Tas tasb2= new Tas(20.0,0,"Tas",0);
        Makas makasb2= new Makas(20.0,0,"Makas",2);
        Kagit kagitb2=new Kagit(20.0,0,"Kagit",2);
        
        bilgisayartemp.nesneListesi.add(tasb);
        bilgisayartemp.nesneListesi.add(kagitb);
        bilgisayartemp.nesneListesi.add(makasb);
        bilgisayartemp.nesneListesi.add(tasb2);
        bilgisayartemp.nesneListesi.add(makasb2);
        bilgisayartemp.nesneListesi.add(kagitb2);
        
        Random rnd= new Random();
        
        int i=rnd.nextInt(3);
        
        bilgisayar1.nesneListesi.add(0,bilgisayartemp.nesneListesi.get(i));
        
        int j;
        
       
           
       while(true)
       {
           j=rnd.nextInt(3);
           bilgisayar1.nesneListesi.add(1,bilgisayartemp.nesneListesi.get(j));
           if(j!=i){
               break;
           }
       }
           
          
       
       int k;
        
       
       while(true){
             k=rnd.nextInt(3);
           bilgisayar1.nesneListesi.add(2,bilgisayartemp.nesneListesi.get(k));
           if(k!=i && k!=j){
               break;
           }
       }
        
        int l=rnd.nextInt(4);
        bilgisayar1.nesneListesi.add(3,bilgisayartemp.nesneListesi.get(l));
        int m=rnd.nextInt(4);
         bilgisayar1.nesneListesi.add(4,bilgisayartemp.nesneListesi.get(m));
        
         for(int z=0;z<5;z++){
        
             System.out.println(bilgisayar1.nesneListesi.get(z).isim);
        
    }
        
  
    }//GEN-LAST:event_nesneolustur1ActionPerformed

    private void nesneolustur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nesneolustur2ActionPerformed
        // TODO add your handling code here:
        Tas tasb= new Tas(20,2,"Tas",5);
        Kagit kagitb= new Kagit(20,2,"Kagit",5);
        Makas makasb= new Makas(20,2,"Makas",3);
        
        Tas tasb2= new Tas(20,2,"Tas",5);
        Makas makasb2= new Makas(20,2,"Makas",3);
        Kagit kagitb2=new Kagit(20,2,"Kagit",5);
        
        
        bilgisayartemp.nesneListesi.add(tasb);
        bilgisayartemp.nesneListesi.add(kagitb);
        bilgisayartemp.nesneListesi.add(makasb);
        bilgisayartemp.nesneListesi.add(tasb2);
        bilgisayartemp.nesneListesi.add(makasb2);
        bilgisayartemp.nesneListesi.add(kagitb2);
        
        Random rnd= new Random();
        
        int i=rnd.nextInt(3);
        
        oyuncu1.nesneListesi.add(0,bilgisayartemp.nesneListesi.get(i));
        
        int j;
        
       
           
       while(true)
       {
           j=rnd.nextInt(3);
           oyuncu1.nesneListesi.add(1,bilgisayartemp.nesneListesi.get(j));
           if(j!=i){
               break;
           }
       }
           
          
       
       int k;
        
       
       while(true){
             k=rnd.nextInt(3);
           oyuncu1.nesneListesi.add(2,bilgisayartemp.nesneListesi.get(k));
           if(k!=i && k!=j){
               break;
           }
       }
        
        int l=rnd.nextInt(4);
        oyuncu1.nesneListesi.add(3,bilgisayartemp.nesneListesi.get(l));
        int m=rnd.nextInt(4);
         oyuncu1.nesneListesi.add(4,bilgisayartemp.nesneListesi.get(m));
        
         for(int z=0;z<5;z++){
        
             System.out.println(oyuncu1.nesneListesi.get(z).isim);
        
    }
         
    }//GEN-LAST:event_nesneolustur2ActionPerformed

    private void hamleyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamleyapActionPerformed
       
        
         // TODO add your handling code here:
        Random rnd= new Random();
        int i= rnd.nextInt(5);
        int j= rnd.nextInt(5);
        jLabel1.setText(bilgisayar1.nesneListesi.get(i).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(j).isim);
        
        
        
        
        if((oyuncu1.nesneListesi.get(j).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="Makas")){
            
            oyuncu1.nesneListesi.get(j).seviyePuani+=20;
           
            
            // taşın makasa etkisi
           double etki= oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik);
           
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
       
           
           //makasın taşa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).katilik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
            double a;
            a=oyuncu1.nesneListesi.get(j).dayaniklilik;
            System.out.println(a);
            if(oyuncu1.nesneListesi.get(j).seviyePuani>30 && oyuncu1.nesneListesi.get(j).seviyePuani<42){
            
            AgirTas agirtas1 =new AgirTas(a,oyuncu1.nesneListesi.get(j).seviyePuani,"AgirTas",2,2);
            oyuncu1.nesneListesi.set(j,agirtas1);
            
        }
                   
 
        
        }
        
        //*************************************
        
        if(oyuncu1.nesneListesi.get(j).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit" ){
           
           // Taşın kağıta etkisi
           bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
            double a;
            a=bilgisayar1.nesneListesi.get(i).dayaniklilik;
            

           // Kağıdın taşa etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).katilik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
           
           if(bilgisayar1.nesneListesi.get(i).seviyePuani>30 && bilgisayar1.nesneListesi.get(i).seviyePuani<42){
               
            
            OzelKagit ozelkagitb =new OzelKagit(a,bilgisayar1.nesneListesi.get(i).seviyePuani,"OzelKagit",2,2);
            bilgisayar1.nesneListesi.set(i,ozelkagitb);
            
        }
           
           
     
               
            
            
            
        }
       
       //*********************************************
       
        if(oyuncu1.nesneListesi.get(j).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="Tas"){
   
            bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
            // makasın taşa etkisi
            
             double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             double a;
            a=bilgisayar1.nesneListesi.get(i).dayaniklilik;
            
            
             
             //taşın makasa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).keskinlik);
             oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
             

                
                if(bilgisayar1.nesneListesi.get(i).seviyePuani>30 && bilgisayar1.nesneListesi.get(i).seviyePuani<42){
                    
            
            
            AgirTas agirtasb =new AgirTas(a,bilgisayar1.nesneListesi.get(i).seviyePuani,"AgirTas",2,2);
            bilgisayar1.nesneListesi.set(i,agirtasb);
            
        }
                
                
                
            
        }
        
        //*************************************************************
       
       if(oyuncu1.nesneListesi.get(j).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit"){
           
           oyuncu1.nesneListesi.get(j).seviyePuani+=20;
           //makasın kağıta etkisi
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
      
           
           // kağıtın makasa etkisi
        
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).keskinlik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           double a;
            a=oyuncu1.nesneListesi.get(j).dayaniklilik;
           
           if(oyuncu1.nesneListesi.get(j).seviyePuani>30 && oyuncu1.nesneListesi.get(j).seviyePuani<42){
             
            UstaMakas ustamakas1 =new UstaMakas(a,oyuncu1.nesneListesi.get(j).seviyePuani,"UstaMakas",2,2);
            oyuncu1.nesneListesi.set(j,ustamakas1);
            
        }
           
           
      
                
                
                
                 

           
       }
       
       //**************************************************************************************
       
       if(oyuncu1.nesneListesi.get(j).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="Tas"){
           oyuncu1.nesneListesi.get(j).seviyePuani+=20;
           // kağıtın taşa etkisi
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
          // jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           
           //taşın kağıta etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).nufuz);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
            double a;
            a=oyuncu1.nesneListesi.get(j).dayaniklilik;
            
            if(oyuncu1.nesneListesi.get(j).seviyePuani>30 && oyuncu1.nesneListesi.get(j).seviyePuani<42){
             
            OzelKagit ozelkagit1 =new OzelKagit(a,oyuncu1.nesneListesi.get(j).seviyePuani,"OzelKagit",2,2);
            oyuncu1.nesneListesi.set(j,ozelkagit1);
            
        }
            
        
                 
                        
           
       }
       
       //**************************************************************************************
       
       
       
           if(oyuncu1.nesneListesi.get(j).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="Makas"){
                
                bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
               //Kağıtın Makasa etkisi
               double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
                double a;
                a=bilgisayar1.nesneListesi.get(i).dayaniklilik;
               
               
               //Makasın kağıta etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).nufuz);
               oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;

                
               if(bilgisayar1.nesneListesi.get(i).seviyePuani>30 && bilgisayar1.nesneListesi.get(i).seviyePuani<42){
            UstaMakas ustamakasb =new UstaMakas(a,bilgisayar1.nesneListesi.get(i).seviyePuani,"UstaMakas",2,2);
            bilgisayar1.nesneListesi.set(i,ustamakasb);
            
        }
                
       }
           
           
           
           
           //******************************************************
           
           
           
           
           
           
           
        if((oyuncu1.nesneListesi.get(j).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit")){
            
            //taşın özel kağıta etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;


           // özel Kağıdın taşa etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).katilik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
           
           
           
          
            
        }   
        
        
        
        //***************************************************************
        
        if((oyuncu1.nesneListesi.get(j).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="Tas")){
            
            //özel kağıtın taşa etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;


           // taşın özel kağıta etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).nufuz,oyuncu1.nesneListesi.get(j).keskinlik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
           
           
           
  
            
        }   
        
        
        
        
        
        
          //***************************************************************
           
          
          if((oyuncu1.nesneListesi.get(j).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas")){
            
            
            
            // taşın makasa etkisi
           double etki= oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
           
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
         
           
           //usta makasın taşa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).katilik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
                   
                   
                   
            
        
        }
          
          //*********************************************************
          
          
          if((oyuncu1.nesneListesi.get(j).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="Tas")){
            
            
            
            // usta makasın taşa etkisi
           double etki= oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik);
           
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           
           
           //taşın usta makasa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).keskinlik,oyuncu1.nesneListesi.get(j).direnc);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
                   
                   
        
        
        }
          
          
          
          
          
          
          
          
          //**********************************************************************************************
          
          
          
          
          if(oyuncu1.nesneListesi.get(j).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas"){
          
         
           // kağıtın ağır taşa etkisi
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           
           
           
           //ağır taşın kağıta etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).nufuz);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
            
            
     
           
       }
          
          //**************************************************************
          
          
          
          
          
          if(oyuncu1.nesneListesi.get(j).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit"){
          
         
           // ağırtaşın kağıta etkisi
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
          
           
           
           //kağıtın ağır taşa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).katilik,oyuncu1.nesneListesi.get(j).direnc);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
            
            

           
       
           
       }
          
          
          
          
          
          
          
          
          
          
          //*****************************************************************************
          
          
          
          if(oyuncu1.nesneListesi.get(j).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas"){
                
                
               
               //Kağıtın Makasa etkisi
               double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
              
               
               //usta Makasın kağıta etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).nufuz);
               oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
          
               
                
       }
          
          
          //*************************************************************
          
          
          
          if(oyuncu1.nesneListesi.get(j).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit"){
                
                
               
               //usta makasın kağıta etkisi
               double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
            
               
               //kağıtın usta makasa etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).keskinlik,oyuncu1.nesneListesi.get(j).direnc);
               oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
      
                 
               
                
       }
          
          
          
          //**************************************************************
          
          
          
          if(oyuncu1.nesneListesi.get(j).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas"){
           
            // makasın ağır taşa etkisi
            
             double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
      
            
             
             //ağır taşın makasa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).keskinlik);
             oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
             
      
                
               
             
        }
          
          
          
          //****************************************************************
          
          
          
          
          
          
           if(oyuncu1.nesneListesi.get(j).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="Makas"){
           
            // ağır taşın makasa etkisi
            
             double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
                 
            
             
             //makasın ağır taşa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).katilik,oyuncu1.nesneListesi.get(j).sicaklik);
             oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
             
        
                
               
             
        }
       
          
          
          
          
          //********************************************************************
          
          
          
          
           if(oyuncu1.nesneListesi.get(j).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit"){
           
           //makasın özel kağıta etkisi
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           
           
           // özel kağıtın makasa etkisi
        
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).keskinlik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
            
           
       
              
           
       }
           
           
           //*******************************************************
           
           
           
           
           
           
           if(oyuncu1.nesneListesi.get(j).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="Makas"){
           
           //özel kağıtın makasa etkisi
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
         
           
           // makasın özel kağıta etkisi
        
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).nufuz,oyuncu1.nesneListesi.get(j).kalinlik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
            
           
          
              
           
       }
           
           
           
           
       
           
           
           
            //******************************************************
           
           
           
           
           
           
           
        if((oyuncu1.nesneListesi.get(j).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit")){
            bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
            //ağır taşın özel kağıta etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
       

           // özel Kağıdın ağır  taşa etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).katilik,oyuncu1.nesneListesi.get(j).sicaklik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
           
           
           
         
            
        }
        
        
        
        //*************************************************************************************
        
        
        
        if((oyuncu1.nesneListesi.get(j).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas")){
            oyuncu1.nesneListesi.get(i).seviyePuani+=20;
            
            
            //özelkağıtın ağır taşa etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
       

           // ağır taşın özel kağıta etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).nufuz,oyuncu1.nesneListesi.get(j).kalinlik);
           oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
           
            
            
        }  
        
        
        
        
        
        
        
        
        
        
        
        
          //***************************************************************
           
           
           
           
           if(oyuncu1.nesneListesi.get(j).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas"){
                
                bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
            // usta makasın ağır taşa etkisi
            
             double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
         
            
             
             //ağır taşın makasa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).keskinlik);
             oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
             
        
                
               
             
           }
           
           
           
           
           //***********************************************************
           
           
           
            if(oyuncu1.nesneListesi.get(j).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas"){
                
                oyuncu1.nesneListesi.get(i).seviyePuani+=20;
               
            // ağırtaşın ustamakasa etkisi
            
             double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             
            
             
             //usta makasın ağır taşa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).katilik,oyuncu1.nesneListesi.get(j).sicaklik);
             oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
             
            
                
               
             
           }
           
           
           
           
           
           
           
           //*************************************************************************
           
           
           
            if(oyuncu1.nesneListesi.get(j).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas"){
                
                 bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
               //özel Kağıtın Makasa etkisi
               double etki=oyuncu1.nesneListesi.get(j).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
            
               
               //usta Makasın özel kağıta etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(2).etkiHesaplaguclu(oyuncu1.nesneListesi.get(j).nufuz,oyuncu1.nesneListesi.get(j).kalinlik);
               oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
               
                 
               
                
       }
           
            
            if(oyuncu1.nesneListesi.get(j).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit"){
                
                 bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
               //usta makasın özel kağıta etkisi
               double etki=oyuncu1.nesneListesi.get(j).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             
               
               //özel kağıtın usta makasa etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(2).etkiHesaplazayif(oyuncu1.nesneListesi.get(j).keskinlik,oyuncu1.nesneListesi.get(j).direnc);
               oyuncu1.nesneListesi.get(j).dayaniklilik=oyuncu1.nesneListesi.get(j).dayaniklilik-etki2;
               
               
                
       }
            jLabel5.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
            jLabel6.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).seviyePuani));
            jLabel7.setText(String.valueOf(oyuncu1.nesneListesi.get(j).dayaniklilik));
            jLabel8.setText(String.valueOf(oyuncu1.nesneListesi.get(j).seviyePuani));
            
            
            hamlesayisi++;
           
           if(hamlesayisi>10){
               jLabel13.setText("10 hamle yaptınız.");
               
               if(oyuncu1.nesneListesi.get(0).dayaniklilik<=0 &&oyuncu1.nesneListesi.get(1).dayaniklilik<=0&&oyuncu1.nesneListesi.get(2).dayaniklilik<=0&&oyuncu1.nesneListesi.get(3).dayaniklilik<=0&&oyuncu1.nesneListesi.get(4).dayaniklilik<=0){
               
               
             jLabel14.setText("Bilgisayar2 Kazandı");
           }
           
           if(bilgisayar1.nesneListesi.get(0).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(1).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(2).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(3).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(4).dayaniklilik<=0){
               jLabel14.setText("Bilgisayar1 Kazandı");
           }
               
               for(int z=0;z<5;z++){
                   oyuncudayanikliliksayac=oyuncudayanikliliksayac+oyuncu1.nesneListesi.get(z).dayaniklilik;
                   bilgisayardayanikliliksayac=bilgisayardayanikliliksayac+bilgisayar1.nesneListesi.get(z).dayaniklilik;
               }
               
               if(oyuncudayanikliliksayac>bilgisayardayanikliliksayac){
                   jLabel14.setText("Bilgisayar1 Kazandı");
               }
               if(bilgisayardayanikliliksayac>oyuncudayanikliliksayac){
                   jLabel14.setText("Bilgisayar2 Kazandı");
               }
               
           }
           
           
           
           
           
           
           
           
           
        
        
        
        
    }//GEN-LAST:event_hamleyapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bilgisayar_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bilgisayar_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bilgisayar_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bilgisayar_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bilgisayar_Bilgisayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hamleyap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton nesneolustur1;
    private javax.swing.JButton nesneolustur2;
    // End of variables declaration//GEN-END:variables
}
