package javaapplication53;
import javax.swing.JPanel;
import javax.swing.JFrame;
import java.util.Random;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author blnyp
 */

public class Kullanici_Bilgisayar extends javax.swing.JFrame {
    
    int oyuncuskor=0;
    int bilgisayarskor=0;
    int hamlesayisi=0;
    double oyuncudayanikliliksayac=0;
    double bilgisayardayanikliliksayac=0;
    
    Oyuncu oyuncu1= new Oyuncu() {
        @Override
        void nesneSec() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    };
    
    Bilgisayar bilgisayar1= new Bilgisayar();
    Bilgisayar bilgisayartemp=new Bilgisayar();
    int secim;
    /**
     * Creates new form Kullanici_Bilgisayar
     */
    public Kullanici_Bilgisayar() {
        
        initComponents();
        
        
        oyuncu1.oyuncuID=1;
        oyuncu1.oyuncuAdi="Ahmet";
        oyuncu1.skor=0;
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ilkpanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        tasolustur = new javax.swing.JButton();
        kagitolustur = new javax.swing.JButton();
        makasolustur = new javax.swing.JButton();
        oyna = new javax.swing.JButton();
        ikincipanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hamleyap = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sec1 = new javax.swing.JButton();
        sec2 = new javax.swing.JButton();
        sec3 = new javax.swing.JButton();
        sec4 = new javax.swing.JButton();
        sec5 = new javax.swing.JButton();
        dayaniklilik1 = new javax.swing.JLabel();
        dayaniklilik2 = new javax.swing.JLabel();
        dayaniklilik3 = new javax.swing.JLabel();
        dayaniklilik4 = new javax.swing.JLabel();
        dayaniklilik5 = new javax.swing.JLabel();
        seviyep1 = new javax.swing.JLabel();
        seviyep2 = new javax.swing.JLabel();
        seviyep3 = new javax.swing.JLabel();
        seviyep4 = new javax.swing.JLabel();
        seviyep5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ilkpanel.setBackground(new java.awt.Color(255, 204, 255));

        jTextField1.setBackground(new java.awt.Color(204, 102, 255));
        jTextField1.setText("    5 Tane Nesne Seçiniz");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tasolustur.setBackground(new java.awt.Color(204, 102, 255));
        tasolustur.setText("Taş");
        tasolustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasolusturActionPerformed(evt);
            }
        });

        kagitolustur.setBackground(new java.awt.Color(204, 102, 255));
        kagitolustur.setText("Kağıt");
        kagitolustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kagitolusturActionPerformed(evt);
            }
        });

        makasolustur.setBackground(new java.awt.Color(204, 102, 255));
        makasolustur.setText("Makas");
        makasolustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makasolusturActionPerformed(evt);
            }
        });

        oyna.setBackground(new java.awt.Color(204, 0, 102));
        oyna.setText("OYNA");
        oyna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oynaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ilkpanelLayout = new javax.swing.GroupLayout(ilkpanel);
        ilkpanel.setLayout(ilkpanelLayout);
        ilkpanelLayout.setHorizontalGroup(
            ilkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ilkpanelLayout.createSequentialGroup()
                .addGroup(ilkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ilkpanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(ilkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kagitolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tasolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makasolustur, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ilkpanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(oyna, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ilkpanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        ilkpanelLayout.setVerticalGroup(
            ilkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ilkpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(tasolustur)
                .addGap(46, 46, 46)
                .addComponent(kagitolustur)
                .addGap(41, 41, 41)
                .addComponent(makasolustur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oyna)
                .addGap(67, 67, 67))
        );

        ikincipanel.setBackground(new java.awt.Color(255, 204, 255));

        jTextField2.setBackground(new java.awt.Color(204, 102, 255));
        jTextField2.setText("  Kullanıcı");

        jTextField3.setBackground(new java.awt.Color(204, 102, 255));
        jTextField3.setText(" Bilgisayar");

        jLabel6.setText("Seçilen Nesne");

        hamleyap.setBackground(new java.awt.Color(204, 0, 102));
        hamleyap.setText("HAMLE YAP");
        hamleyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamleyapActionPerformed(evt);
            }
        });

        jLabel7.setText("Seçilen Nesne");

        jLabel8.setText("Seçilen Nesne");

        sec1.setText("Seç");
        sec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec1ActionPerformed(evt);
            }
        });

        sec2.setText("Seç");
        sec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec2ActionPerformed(evt);
            }
        });

        sec3.setText("Seç");
        sec3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec3ActionPerformed(evt);
            }
        });

        sec4.setText("Seç");
        sec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec4ActionPerformed(evt);
            }
        });

        sec5.setText("Seç");
        sec5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec5ActionPerformed(evt);
            }
        });

        jTextField4.setText("Nesne ismi");

        jTextField5.setText("Dayanıklılık");

        jTextField6.setText("Seviye Puanı");

        jTextField7.setText("Dayanıklılık");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setText("Seviye Puanı");

        javax.swing.GroupLayout ikincipanelLayout = new javax.swing.GroupLayout(ikincipanel);
        ikincipanel.setLayout(ikincipanelLayout);
        ikincipanelLayout.setHorizontalGroup(
            ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikincipanelLayout.createSequentialGroup()
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dayaniklilik5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(dayaniklilik4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dayaniklilik2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dayaniklilik1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dayaniklilik3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ikincipanelLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ikincipanelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                                .addComponent(seviyep5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sec5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(seviyep4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(seviyep2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(seviyep3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(seviyep1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sec4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sec3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(ikincipanelLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikincipanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikincipanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikincipanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikincipanelLayout.createSequentialGroup()
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hamleyap, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(60, 60, 60)))))
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikincipanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(53, 53, 53))
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6)
                                    .addGroup(ikincipanelLayout.createSequentialGroup()
                                        .addComponent(jTextField7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))
                                    .addGroup(ikincipanelLayout.createSequentialGroup()
                                        .addComponent(jTextField8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)))))
                        .addContainerGap())))
            .addGroup(ikincipanelLayout.createSequentialGroup()
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        ikincipanelLayout.setVerticalGroup(
            ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ikincipanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dayaniklilik1)
                            .addComponent(seviyep1)
                            .addComponent(sec1)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(dayaniklilik2)
                                .addComponent(seviyep2))
                            .addComponent(sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(dayaniklilik3)
                                    .addComponent(seviyep3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(dayaniklilik4)
                                    .addComponent(seviyep4)))
                            .addGroup(ikincipanelLayout.createSequentialGroup()
                                .addComponent(sec4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sec3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dayaniklilik5)
                            .addComponent(seviyep5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sec5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8)))
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ikincipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ikincipanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hamleyap)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ilkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ikincipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ikincipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ilkpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makasolusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makasolusturActionPerformed
        // TODO add your handling code here:
        Makas makas1=new Makas(20.0,0,"Makas",2);

        oyuncu1.nesneListesi.add(makas1);

    }//GEN-LAST:event_makasolusturActionPerformed

    private void kagitolusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kagitolusturActionPerformed

        // TODO add your handling code here:
        Kagit kagit1=new Kagit(20.0,0,"Kagit",2);

        oyuncu1.nesneListesi.add(kagit1);

    }//GEN-LAST:event_kagitolusturActionPerformed

    private void tasolusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasolusturActionPerformed
        // TODO add your handling code here:

        Tas tas1=new Tas(20.0,0,"Tas",2);

        oyuncu1.nesneListesi.add(tas1);

    }//GEN-LAST:event_tasolusturActionPerformed

    private void oynaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oynaActionPerformed
        // TODO add your handling code here:
        ikincipanel.setVisible(true);
        ilkpanel.setVisible(false);
        
        jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
        
        
        dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
        dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
        dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
        dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
        dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
        
        
        seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
        seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
        seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
        seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
        seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
        
       
        
       Tas tasb= new Tas(20.0,0,"Tas",2);
        Kagit kagitb= new Kagit(20.0,0,"Kagit",2);
        Makas makasb= new Makas(20.0,0,"Makas",2);
        
        Tas tasb2= new Tas(20.0,0,"Tas",0);
        Makas makasb2= new Makas(20.0,0,"Makas",2);
        Kagit kagitb2=new Kagit(20.0,0,"Kagit",2);
        
        bilgisayartemp.nesneListesi.add(tasb);
        bilgisayartemp.nesneListesi.add(kagitb);
        bilgisayartemp.nesneListesi.add(makasb);
        bilgisayartemp.nesneListesi.add(tasb2);
        bilgisayartemp.nesneListesi.add(makasb2);
        bilgisayartemp.nesneListesi.add(kagitb2);
        
        Random rnd= new Random();
        
        int i=rnd.nextInt(3);
        
        bilgisayar1.nesneListesi.add(0,bilgisayartemp.nesneListesi.get(i));
        
        int j;
        
       
           
       while(true)
       {
           j=rnd.nextInt(3);
           bilgisayar1.nesneListesi.add(1,bilgisayartemp.nesneListesi.get(j));
           if(j!=i){
               break;
           }
       }
           
          
       
       int k;
        
       
       while(true){
             k=rnd.nextInt(3);
           bilgisayar1.nesneListesi.add(2,bilgisayartemp.nesneListesi.get(k));
           if(k!=i && k!=j){
               break;
           }
       }
        
        int l=rnd.nextInt(4);
        bilgisayar1.nesneListesi.add(3,bilgisayartemp.nesneListesi.get(l));
        int m=rnd.nextInt(4);
         bilgisayar1.nesneListesi.add(4,bilgisayartemp.nesneListesi.get(m));
        
        
         
        
    }//GEN-LAST:event_oynaActionPerformed

    private void sec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec1ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(oyuncu1.nesneListesi.get(0).isim);
        secim=0;
        
    }//GEN-LAST:event_sec1ActionPerformed

    private void sec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec2ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(oyuncu1.nesneListesi.get(1).isim);
        secim=1;
    }//GEN-LAST:event_sec2ActionPerformed

    private void sec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec3ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(oyuncu1.nesneListesi.get(2).isim);
        secim=2;
    }//GEN-LAST:event_sec3ActionPerformed

    private void sec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec4ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(oyuncu1.nesneListesi.get(3).isim);
        secim=3;
    }//GEN-LAST:event_sec4ActionPerformed

    private void sec5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec5ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(oyuncu1.nesneListesi.get(4).isim);
        secim=4;
    }//GEN-LAST:event_sec5ActionPerformed

    private void hamleyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamleyapActionPerformed
        // TODO add your handling code here:
        Random rnd= new Random();
        int i= rnd.nextInt(4);
        
        jLabel6.setText(bilgisayar1.nesneListesi.get(i).isim);
        jLabel8.setText(bilgisayar1.nesneListesi.get(i).isim);

        
        if((oyuncu1.nesneListesi.get(secim).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="Makas")){
            oyuncuskor++;
            oyuncu1.nesneListesi.get(secim).seviyePuani+=20;
           
            
            // taşın makasa etkisi
           double etki= oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik);
           
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           //makasın taşa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).katilik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
            double a;
            a=oyuncu1.nesneListesi.get(secim).dayaniklilik;
            System.out.println(a);
            if(oyuncu1.nesneListesi.get(secim).seviyePuani>30 && oyuncu1.nesneListesi.get(secim).seviyePuani<42){
            
            AgirTas agirtas1 =new AgirTas(a,oyuncu1.nesneListesi.get(secim).seviyePuani,"AgirTas",2,2);
            oyuncu1.nesneListesi.set(secim,agirtas1);
            
        }
                   
                   
                 jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
             
        
        }
        
        //*************************************
        
        if(oyuncu1.nesneListesi.get(secim).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit" ){
           
           // Taşın kağıta etkisi
           bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
            double a;
            a=bilgisayar1.nesneListesi.get(i).dayaniklilik;
            
           //jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));

           // Kağıdın taşa etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).katilik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
           
           if(bilgisayar1.nesneListesi.get(i).seviyePuani>30 && bilgisayar1.nesneListesi.get(i).seviyePuani<42){
               
            
            OzelKagit ozelkagitb =new OzelKagit(a,bilgisayar1.nesneListesi.get(i).seviyePuani,"OzelKagit",2,2);
            bilgisayar1.nesneListesi.set(i,ozelkagitb);
            
        }
           
           
            jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
            dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));    
            dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
            dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik)); 
            dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
            seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
            seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
            seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
            seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
            seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
         
               
            
            
            
        }
       
       //*********************************************
       
        if(oyuncu1.nesneListesi.get(secim).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="Tas"){
            bilgisayarskor++;
            bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
            // makasın taşa etkisi
            
             double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             double a;
            a=bilgisayar1.nesneListesi.get(i).dayaniklilik;
             jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));      
            
             
             //taşın makasa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).keskinlik);
             oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
             
              dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                if(bilgisayar1.nesneListesi.get(i).seviyePuani>30 && bilgisayar1.nesneListesi.get(i).seviyePuani<42){
                    
            
            
            AgirTas agirtasb =new AgirTas(a,bilgisayar1.nesneListesi.get(i).seviyePuani,"AgirTas",2,2);
            bilgisayar1.nesneListesi.set(i,agirtasb);
            
        }
                
                
                
            
        }
        
        //*************************************************************
       
       if(oyuncu1.nesneListesi.get(secim).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit"){
           
           oyuncu1.nesneListesi.get(secim).seviyePuani+=20;
           //makasın kağıta etkisi
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           // kağıtın makasa etkisi
        
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).keskinlik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           double a;
            a=oyuncu1.nesneListesi.get(secim).dayaniklilik;
           
           if(oyuncu1.nesneListesi.get(secim).seviyePuani>30 && oyuncu1.nesneListesi.get(secim).seviyePuani<42){
             
            UstaMakas ustamakas1 =new UstaMakas(a,oyuncu1.nesneListesi.get(secim).seviyePuani,"UstaMakas",2,2);
            oyuncu1.nesneListesi.set(secim,ustamakas1);
            
        }
           
           
           jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
           
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
             
                
                
                
                 

           
       }
       
       //**************************************************************************************
       
       if(oyuncu1.nesneListesi.get(secim).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="Tas"){
           oyuncu1.nesneListesi.get(secim).seviyePuani+=20;
           // kağıtın taşa etkisi
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
          // jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           
           //taşın kağıta etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).nufuz);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
            double a;
            a=oyuncu1.nesneListesi.get(secim).dayaniklilik;
            
            if(oyuncu1.nesneListesi.get(secim).seviyePuani>30 && oyuncu1.nesneListesi.get(secim).seviyePuani<42){
             
            OzelKagit ozelkagit1 =new OzelKagit(a,oyuncu1.nesneListesi.get(secim).seviyePuani,"OzelKagit",2,2);
            oyuncu1.nesneListesi.set(secim,ozelkagit1);
            
        }
            
            jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
           
           
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
                 
                        
           
       }
       
       //**************************************************************************************
       
       
       
           if(oyuncu1.nesneListesi.get(secim).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="Makas"){
                bilgisayarskor++;
                bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
               //Kağıtın Makasa etkisi
               double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
                double a;
                a=bilgisayar1.nesneListesi.get(i).dayaniklilik;
               jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
               
               //Makasın kağıta etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).nufuz);
               oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
               dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
               
                
               if(bilgisayar1.nesneListesi.get(i).seviyePuani>30 && bilgisayar1.nesneListesi.get(i).seviyePuani<42){
            UstaMakas ustamakasb =new UstaMakas(a,bilgisayar1.nesneListesi.get(i).seviyePuani,"UstaMakas",2,2);
            bilgisayar1.nesneListesi.set(i,ustamakasb);
            
        }
                
       }
           
           
           
           
           //******************************************************
           
           
           
           
           
           
           
        if((oyuncu1.nesneListesi.get(secim).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit")){
            
            //taşın özel kağıta etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));

           // özel Kağıdın taşa etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).katilik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
           
           
           
            jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
            jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
            jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
            jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
            jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
            dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));    
            dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
            dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik)); 
            dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
            seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
            seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
            seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
            seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
            seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
            
        }   
        
        
        
        //***************************************************************
        
        if((oyuncu1.nesneListesi.get(secim).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="Tas")){
            
            //özel kağıtın taşa etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));

           // taşın özel kağıta etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).nufuz,oyuncu1.nesneListesi.get(secim).keskinlik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
           
           
           
            jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
            jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
            jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
            jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
            jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
            dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));    
            dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
            dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik)); 
            dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
            seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
            seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
            seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
            seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
            seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
            
        }   
        
        
        
        
        
        
          //***************************************************************
           
          
          if((oyuncu1.nesneListesi.get(secim).isim=="Tas" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas")){
            
            
            
            // taşın makasa etkisi
           double etki= oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
           
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           //usta makasın taşa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).katilik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
                   
                   
                   
                 jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
         
        
        }
          
          //*********************************************************
          
          
          if((oyuncu1.nesneListesi.get(secim).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="Tas")){
            
            
            
            // usta makasın taşa etkisi
           double etki= oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik);
           
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           //taşın usta makasa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).keskinlik,oyuncu1.nesneListesi.get(secim).direnc);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
                   
                   
                   
                 jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
          
        
        }
          
          
          
          
          
          
          
          
          //**********************************************************************************************
          
          
          
          
          if(oyuncu1.nesneListesi.get(secim).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas"){
          
         
           // kağıtın ağır taşa etkisi
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           
           //ağır taşın kağıta etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).nufuz);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
            
            
        jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
           
           
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
    
           
       }
          
          //**************************************************************
          
          
          
          
          
          if(oyuncu1.nesneListesi.get(secim).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit"){
          
         
           // ağırtaşın kağıta etkisi
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           
           //kağıtın ağır taşa etkisi
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).katilik,oyuncu1.nesneListesi.get(secim).direnc);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
            
            
        jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
           
           
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));

           
       }
          
          
          
          
          
          
          
          
          
          
          //*****************************************************************************
          
          
          
          if(oyuncu1.nesneListesi.get(secim).isim=="Kagit" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas"){
                
                
               
               //Kağıtın Makasa etkisi
               double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
               jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
               
               //usta Makasın kağıta etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).nufuz);
               oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
               dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                 
               
                
       }
          
          
          //*************************************************************
          
          
          
          if(oyuncu1.nesneListesi.get(secim).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="Kagit"){
                
                
               
               //usta makasın kağıta etkisi
               double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
               jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
               
               //kağıtın usta makasa etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).keskinlik,oyuncu1.nesneListesi.get(secim).direnc);
               oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
               dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                 
               
                
       }
          
          
          
          //**************************************************************
          
          
          
          if(oyuncu1.nesneListesi.get(secim).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas"){
           
            // makasın ağır taşa etkisi
            
             double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));      
            
             
             //ağır taşın makasa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).keskinlik);
             oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
             
              dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
               
             
        }
          
          
          
          //****************************************************************
          
          
          
          
          
          
           if(oyuncu1.nesneListesi.get(secim).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="Makas"){
           
            // ağır taşın makasa etkisi
            
             double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));      
            
             
             //makasın ağır taşa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).katilik,oyuncu1.nesneListesi.get(secim).sicaklik);
             oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
             
              dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
               
             
        }
       
          
          
          
          
          //********************************************************************
          
          
          
          
           if(oyuncu1.nesneListesi.get(secim).isim=="Makas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit"){
           
           //makasın özel kağıta etkisi
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           // özel kağıtın makasa etkisi
        
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).keskinlik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
            
           
           jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
           
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
           
           
       }
           
           
           //*******************************************************
           
           
           
           
           
           
           if(oyuncu1.nesneListesi.get(secim).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="Makas"){
           
           //özel kağıtın makasa etkisi
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik);
           bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
           
           // makasın özel kağıta etkisi
        
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).nufuz,oyuncu1.nesneListesi.get(secim).kalinlik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
            
           
           jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
        jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
        jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
        jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
        jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
           
                dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
                seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
                seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
                seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
                seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
                seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
           
           
       }
           
           
           
           
       
           
           
           
            //******************************************************
           
           
           
           
           
           
           
        if((oyuncu1.nesneListesi.get(secim).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit")){
            bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
            //ağır taşın özel kağıta etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));

           // özel Kağıdın ağır  taşa etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).katilik,oyuncu1.nesneListesi.get(secim).sicaklik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
           
           
           
            jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
            jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
            jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
            jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
            jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
            dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));    
            dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
            dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik)); 
            dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
            seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
            seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
            seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
            seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
            seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
            
        }
        
        
        
        //*************************************************************************************
        
        
        
        if((oyuncu1.nesneListesi.get(secim).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas")){
            oyuncu1.nesneListesi.get(i).seviyePuani+=20;
            
            
            //özelkağıtın ağır taşa etkisi
            
           
           double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
            bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
           jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));

           // ağır taşın özel kağıta etkisi
           
           double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).nufuz,oyuncu1.nesneListesi.get(secim).kalinlik);
           oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
           
            jLabel1.setText(oyuncu1.nesneListesi.get(0).isim);
            jLabel2.setText(oyuncu1.nesneListesi.get(1).isim);
            jLabel3.setText(oyuncu1.nesneListesi.get(2).isim);
            jLabel4.setText(oyuncu1.nesneListesi.get(3).isim);
            jLabel5.setText(oyuncu1.nesneListesi.get(4).isim);
            dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
            dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));    
            dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
            dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik)); 
            dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
            seviyep1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).seviyePuani));
            seviyep2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).seviyePuani));
            seviyep3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).seviyePuani));
            seviyep4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).seviyePuani));
            seviyep5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).seviyePuani));
            
        }  
        
        
        
        
        
        
        
        
        
        
        
        
          //***************************************************************
           
           
           
           
           if(oyuncu1.nesneListesi.get(secim).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="AgirTas"){
                
                bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
            // usta makasın ağır taşa etkisi
            
             double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).katilik,bilgisayar1.nesneListesi.get(i).sicaklik);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));      
            
             
             //ağır taşın makasa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).keskinlik);
             oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
             
              dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
               
             
           }
           
           
           
           
           //***********************************************************
           
           
           
            if(oyuncu1.nesneListesi.get(secim).isim=="AgirTas" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas"){
                
                oyuncu1.nesneListesi.get(i).seviyePuani+=20;
               
            // ağırtaşın ustamakasa etkisi
            
             double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
             bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
             jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));      
            
             
             //usta makasın ağır taşa etkisi
             
             double etki2=bilgisayar1.nesneListesi.get(i).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).katilik,oyuncu1.nesneListesi.get(secim).sicaklik);
             oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
             
              dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                
               
             
           }
           
           
           
           
           
           
           
           //*************************************************************************
           
           
           
            if(oyuncu1.nesneListesi.get(secim).isim=="OzelKagit" && bilgisayar1.nesneListesi.get(i).isim=="UstaMakas"){
                
                 bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
               //özel Kağıtın Makasa etkisi
               double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplazayif(bilgisayar1.nesneListesi.get(i).keskinlik,bilgisayar1.nesneListesi.get(i).direnc);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
               jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
               
               //usta Makasın özel kağıta etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(2).etkiHesaplaguclu(oyuncu1.nesneListesi.get(secim).nufuz,oyuncu1.nesneListesi.get(secim).kalinlik);
               oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
               dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                 
               
                
       }
           
            
            if(oyuncu1.nesneListesi.get(secim).isim=="UstaMakas" && bilgisayar1.nesneListesi.get(i).isim=="OzelKagit"){
                
                 bilgisayar1.nesneListesi.get(i).seviyePuani+=20;
               
               //usta makasın özel kağıta etkisi
               double etki=oyuncu1.nesneListesi.get(secim).etkiHesaplaguclu(bilgisayar1.nesneListesi.get(i).nufuz,bilgisayar1.nesneListesi.get(i).kalinlik);
               bilgisayar1.nesneListesi.get(i).dayaniklilik=bilgisayar1.nesneListesi.get(i).dayaniklilik-etki;
               jLabel11.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
               
               //özel kağıtın usta makasa etkisi
               
               double etki2=bilgisayar1.nesneListesi.get(2).etkiHesaplazayif(oyuncu1.nesneListesi.get(secim).keskinlik,oyuncu1.nesneListesi.get(secim).direnc);
               oyuncu1.nesneListesi.get(secim).dayaniklilik=oyuncu1.nesneListesi.get(secim).dayaniklilik-etki2;
               dayaniklilik1.setText(String.valueOf(oyuncu1.nesneListesi.get(0).dayaniklilik));
                dayaniklilik2.setText(String.valueOf(oyuncu1.nesneListesi.get(1).dayaniklilik));
                dayaniklilik3.setText(String.valueOf(oyuncu1.nesneListesi.get(2).dayaniklilik));
                dayaniklilik4.setText(String.valueOf(oyuncu1.nesneListesi.get(3).dayaniklilik));
                dayaniklilik5.setText(String.valueOf(oyuncu1.nesneListesi.get(4).dayaniklilik));
                 
               
                
       }
           
            
            jLabel15.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).dayaniklilik));
            jLabel16.setText(String.valueOf(bilgisayar1.nesneListesi.get(i).seviyePuani));
            
           
           
           hamlesayisi++;
           
           if(hamlesayisi>10){
               jLabel13.setText("10 hamle yaptınız.");
               
               for(int z=0;z<5;z++){
                   oyuncudayanikliliksayac=oyuncudayanikliliksayac+oyuncu1.nesneListesi.get(z).dayaniklilik;
                   bilgisayardayanikliliksayac=bilgisayardayanikliliksayac+bilgisayar1.nesneListesi.get(z).dayaniklilik;
               }
               
               if(oyuncudayanikliliksayac>bilgisayardayanikliliksayac){
                   jLabel14.setText("Oyuncu Kazandı");
               }
               if(bilgisayardayanikliliksayac>oyuncudayanikliliksayac){
                   jLabel14.setText("Bilgisayar Kazandı");
               }
               
           }
           
           
           
           
           if(oyuncu1.nesneListesi.get(0).dayaniklilik<=0 &&oyuncu1.nesneListesi.get(1).dayaniklilik<=0&&oyuncu1.nesneListesi.get(2).dayaniklilik<=0&&oyuncu1.nesneListesi.get(3).dayaniklilik<=0&&oyuncu1.nesneListesi.get(4).dayaniklilik<=0){
               
               
             jLabel14.setText("Oyuncu Kazandı");
           }
           
           if(bilgisayar1.nesneListesi.get(0).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(1).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(2).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(3).dayaniklilik<=0&&bilgisayar1.nesneListesi.get(4).dayaniklilik<=0){
               jLabel14.setText("Bilgisayar Kazandı");
           }
           
   
        
        
    }//GEN-LAST:event_hamleyapActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kullanici_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kullanici_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kullanici_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kullanici_Bilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kullanici_Bilgisayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayaniklilik1;
    private javax.swing.JLabel dayaniklilik2;
    private javax.swing.JLabel dayaniklilik3;
    private javax.swing.JLabel dayaniklilik4;
    private javax.swing.JLabel dayaniklilik5;
    private javax.swing.JButton hamleyap;
    private javax.swing.JPanel ikincipanel;
    private javax.swing.JPanel ilkpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton kagitolustur;
    private javax.swing.JButton makasolustur;
    private javax.swing.JButton oyna;
    private javax.swing.JButton sec1;
    private javax.swing.JButton sec2;
    private javax.swing.JButton sec3;
    private javax.swing.JButton sec4;
    private javax.swing.JButton sec5;
    private javax.swing.JLabel seviyep1;
    private javax.swing.JLabel seviyep2;
    private javax.swing.JLabel seviyep3;
    private javax.swing.JLabel seviyep4;
    private javax.swing.JLabel seviyep5;
    private javax.swing.JButton tasolustur;
    // End of variables declaration//GEN-END:variables
}
